[package]
name = "bits"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "client"
path = "src/client/main.rs"

[[bin]]
name = "server"
path = "src/server/main.rs"

[[example]]
name = "text"
path = "examples/text/main.rs"

[dependencies]
macros = { path = "macros" }
bevy = { version = "0.17.3", features = ["track_location"] }
bevy_egui = "0.38"
bevy-inspector-egui = "0.35.0"
lightyear = { version = "0.25.5", features = [
    "netcode",
    "webtransport",
    "webtransport_dangerous_configuration",
    "input_native",
] }
serde = { version = "1", default-features = false, features = [
    "alloc",
    "derive",
] }
rand = "0.8"
anyhow = "1.0.100"
async-openai = { version = "0.32", default-features = false, features = [
    "responses",
    "rustls",
] }
serde_json = "1.0.148"
schemars = "0.8"
reqwest = { version = "0.12", default-features = false, features = [
    "json",
    "rustls-tls",
] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["fs", "rt", "rt-multi-thread"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3
