apiVersion: v1
kind: Service
metadata:
  name: lobby
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.lobby.service.type }}
  selector:
    app: bits-lobby
  ports:
  - port: {{ .Values.lobby.service.port }}
    targetPort: 8080
    protocol: TCP

