use bevy::prelude::*;
use crate::LetterAnim;

pub const LETTER_SIZE: u32 = 32;

pub fn char_to_letter_anim(c: char) -> LetterAnim {
    match c {
        'a' => LetterAnim::A,
        'b' => LetterAnim::B,
        'c' => LetterAnim::C,
        'd' => LetterAnim::D,
        'e' => LetterAnim::E,
        'f' => LetterAnim::F,
        'g' => LetterAnim::G,
        'h' => LetterAnim::H,
        'i' => LetterAnim::I,
        'j' => LetterAnim::J,
        'k' => LetterAnim::K,
        'l' => LetterAnim::L,
        'm' => LetterAnim::M,
        'n' => LetterAnim::N,
        'o' => LetterAnim::O,
        'p' => LetterAnim::P,
        'q' => LetterAnim::Q,
        'r' => LetterAnim::R,
        's' => LetterAnim::S,
        't' => LetterAnim::T,
        'u' => LetterAnim::U,
        'v' => LetterAnim::V,
        'w' => LetterAnim::W,
        'x' => LetterAnim::X,
        'y' => LetterAnim::Y,
        'z' => LetterAnim::Z,
        'A' => LetterAnim::CapA,
        'B' => LetterAnim::CapB,
        'C' => LetterAnim::CapC,
        'D' => LetterAnim::CapD,
        'E' => LetterAnim::CapE,
        'F' => LetterAnim::CapF,
        'G' => LetterAnim::CapG,
        'H' => LetterAnim::CapH,
        'I' => LetterAnim::CapI,
        'J' => LetterAnim::CapJ,
        'K' => LetterAnim::CapK,
        'L' => LetterAnim::CapL,
        'M' => LetterAnim::CapM,
        'N' => LetterAnim::CapN,
        'O' => LetterAnim::CapO,
        'P' => LetterAnim::CapP,
        'Q' => LetterAnim::CapQ,
        'R' => LetterAnim::CapR,
        'S' => LetterAnim::CapS,
        'T' => LetterAnim::CapT,
        'U' => LetterAnim::CapU,
        'V' => LetterAnim::CapV,
        'W' => LetterAnim::CapW,
        'X' => LetterAnim::CapX,
        'Y' => LetterAnim::CapY,
        'Z' => LetterAnim::CapZ,
        ' ' => LetterAnim::Space,
        '0' => LetterAnim::Zero,
        '1' => LetterAnim::One,
        '2' => LetterAnim::Two,
        '3' => LetterAnim::Three,
        '4' => LetterAnim::Four,
        '5' => LetterAnim::Five,
        '6' => LetterAnim::Six,
        '7' => LetterAnim::Seven,
        '8' => LetterAnim::Eight,
        '9' => LetterAnim::Nine,
        '`' => LetterAnim::Clear,
        '~' => LetterAnim::Back,
        '+' => LetterAnim::Plus,
        '-' => LetterAnim::Minus,
        '*' => LetterAnim::Star,
        _ => {
            warn!("Unknown character '{}', using Space", c);
            LetterAnim::Space
        }
    }
}
